global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance']
  receiver: 'telegram'
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 15m

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '{{ env "TELEGRAM_BOT_TOKEN" }}'
        chat_id: '{{ env "TELEGRAM_CHAT_ID" }}'
        parse_mode: 'HTML'
        message: |
          ğŸŸ  <b>Status:</b> <code>{{ .Status }}</code>
          ğŸ–¥ï¸ <b>Instance:</b> <code>{{ .CommonLabels.instance }}</code>

          ğŸ“ <b>Description:</b>
          {{ .CommonAnnotations.description }}
